export { createCichlidsClient, ApiError } from "./client.js";
export type {
  CichlidsClient,
  CichlidsClientOptions,
  PicturesListParams,
  TanksListParams,
  SpeciesListParams,
  CommunityThreadsListParams,
  PageParams,
  PagedResponse,
  PictureListItem,
  PictureDetail,
  TankListItem,
  TankDetail,
  TankMediaItem,
  Dimensions,
  WaterValues,
  Inhabitant,
  ProfileDetail,
  SpeciesListItem,
  SpeciesDetail,
  CommunityCategory,
  CommunityThreadListItem,
  CommunityThreadDetail,
  CommunityPostDto,
  CommunityAttachment,
  SpeciesLink,
  Comment,
  CommentCreated,
  CreateCommentRequest,
  Me,
} from "./client.js";
