NameVirtualHost *:8080
DirectoryIndex index.php index.htm index.html

<VirtualHost *:8080>
        DocumentRoot	/var/www/html/www-cichlids/cichlids
        ServerName      www.cichlids.com
        ServerAdmin     alex@cichlids.com

        <Directory /var/www/html/www-cichlids/cichlids>
                AllowOverride All
        </Directory>

        <Directory /var/www/html/www-cichlids/cichlids/typo3conf>
		Options Includes FollowSymLinks MultiViews
        </Directory>
        <Directory /var/www/html/www-cichlids/cichlids/typo3temp>
		Options Includes FollowSymLinks MultiViews
        </Directory>

        Alias /p	/var/www/html/www-cichlids/cichlids.extra/static/pics
        Alias /disc  /var/www/html/www-cichlids/cichlids.extra/disc
        Alias /rss   /var/www/html/www-cichlids/cichlids.rss

	#CustomLog /dev/null combined;
</VirtualHost>
