// <auto-generated />
using System;
using System.Collections.Generic;
using Cichlids.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cichlids.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CichlidsDbContext))]
    [Migration("20260709013401_AddPostSpecies")]
    partial class AddPostSpecies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cichlids.Domain.Archive.LegacyComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AuthorLegacyUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_legacy_user_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("CreatedAtLegacy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_legacy");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<int>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<int>("LegacyTargetId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_target_id");

                    b.Property<string>("LegacyTargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legacy_target_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("PosterName")
                        .HasColumnType("text")
                        .HasColumnName("poster_name");

                    b.Property<short?>("Stars")
                        .HasColumnType("smallint")
                        .HasColumnName("stars");

                    b.Property<string>("VaultReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vault_reason");

                    b.HasKey("Id")
                        .HasName("pk_legacy_comment");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_legacy_comment_legacy_id");

                    b.ToTable("legacy_comment", "archive", t =>
                        {
                            t.HasCheckConstraint("ck_legacy_comment_target_type", "legacy_target_type IN ('picture', 'tank')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_collection");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_collection_legacy_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_collection_profile_id");

                    b.ToTable("collection", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.CollectionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("collection_id");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_collection_entry");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_collection_entry_post_id");

                    b.HasIndex("CollectionId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("ix_collection_entry_collection_id_post_id");

                    b.ToTable("collection_entry", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_profile_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedByProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_profile_id");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<string>("PosterName")
                        .HasColumnType("text")
                        .HasColumnName("poster_name");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<long?>("TankId")
                        .HasColumnType("bigint")
                        .HasColumnName("tank_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("AuthorProfileId")
                        .HasDatabaseName("ix_comment_author_profile_id");

                    b.HasIndex("DeletedByProfileId")
                        .HasDatabaseName("ix_comment_deleted_by_profile_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_comment_legacy_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comment_post_id");

                    b.HasIndex("TankId")
                        .HasDatabaseName("ix_comment_tank_id");

                    b.ToTable("comment", "public", t =>
                        {
                            t.HasCheckConstraint("ck_comment_body_not_empty", "body <> ''");

                            t.HasCheckConstraint("ck_comment_exactly_one_target", "(post_id IS NULL) <> (tank_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.CommentVote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_comment_vote");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_comment_vote_profile_id");

                    b.HasIndex("CommentId", "ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_comment_vote_comment_id_profile_id");

                    b.ToTable("comment_vote", "public", t =>
                        {
                            t.HasCheckConstraint("ck_comment_vote_value", "value IN (-1, 1)");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.DiscussionPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_profile_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("PosterName")
                        .HasColumnType("text")
                        .HasColumnName("poster_name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("pk_discussion_post");

                    b.HasIndex("AuthorProfileId")
                        .HasDatabaseName("ix_discussion_post_author_profile_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_discussion_post_legacy_id");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_discussion_post_thread_id");

                    b.ToTable("discussion_post", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.DiscussionPostMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DiscussionPostId")
                        .HasColumnType("bigint")
                        .HasColumnName("discussion_post_id");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_item_id");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_discussion_post_media");

                    b.HasIndex("MediaItemId")
                        .HasDatabaseName("ix_discussion_post_media_media_item_id");

                    b.HasIndex("DiscussionPostId", "MediaItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_discussion_post_media_discussion_post_id_media_item_id");

                    b.ToTable("discussion_post_media", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.DiscussionThread", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastPostAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_post_at");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<int>("PostCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("post_count");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_discussion_thread");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_discussion_thread_legacy_id");

                    b.ToTable("discussion_thread", "public", t =>
                        {
                            t.HasCheckConstraint("ck_discussion_thread_category", "category IN ('cichlids', 'african', 'market_place')");

                            t.HasCheckConstraint("ck_discussion_thread_state", "state IN ('archived', 'open')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Follow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FollowerProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("follower_profile_id");

                    b.Property<long?>("TargetProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_profile_id");

                    b.Property<long?>("TargetTankId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_tank_id");

                    b.HasKey("Id")
                        .HasName("pk_follow");

                    b.HasIndex("TargetProfileId")
                        .HasDatabaseName("ix_follow_target_profile_id");

                    b.HasIndex("TargetTankId")
                        .HasDatabaseName("ix_follow_target_tank_id");

                    b.HasIndex("FollowerProfileId", "TargetProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_follow_follower_profile_id_target_profile_id");

                    b.HasIndex("FollowerProfileId", "TargetTankId")
                        .IsUnique()
                        .HasDatabaseName("ix_follow_follower_profile_id_target_tank_id");

                    b.ToTable("follow", "public", t =>
                        {
                            t.HasCheckConstraint("ck_follow_exactly_one_target", "(target_profile_id IS NULL) <> (target_tank_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Inhabitant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<long?>("SpeciesId")
                        .HasColumnType("bigint")
                        .HasColumnName("species_id");

                    b.Property<long>("TankId")
                        .HasColumnType("bigint")
                        .HasColumnName("tank_id");

                    b.HasKey("Id")
                        .HasName("pk_inhabitant");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_inhabitant_species_id");

                    b.HasIndex("TankId")
                        .HasDatabaseName("ix_inhabitant_tank_id");

                    b.ToTable("inhabitant", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.MediaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ChecksumSha256")
                        .HasColumnType("text")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<long?>("OwnerProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_profile_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_item");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_item_legacy_id");

                    b.HasIndex("OwnerProfileId")
                        .HasDatabaseName("ix_media_item_owner_profile_id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_media_item_storage_key");

                    b.ToTable("media_item", "public", t =>
                        {
                            t.HasCheckConstraint("ck_media_item_kind", "kind IN ('photo', 'video')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.MediaVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_item_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_variant");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_media_variant_storage_key");

                    b.HasIndex("MediaItemId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ix_media_variant_media_item_id_label");

                    b.ToTable("media_variant", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id")
                        .HasName("pk_outbox_event");

                    b.ToTable("outbox_event", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedByProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_profile_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<double?>("RatingAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long?>("TankId")
                        .HasColumnType("bigint")
                        .HasColumnName("tank_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("AuthorProfileId")
                        .HasDatabaseName("ix_post_author_profile_id");

                    b.HasIndex("DeletedByProfileId")
                        .HasDatabaseName("ix_post_deleted_by_profile_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_post_legacy_id");

                    b.HasIndex("TankId")
                        .HasDatabaseName("ix_post_tank_id");

                    b.ToTable("post", "public", t =>
                        {
                            t.HasCheckConstraint("ck_post_kind", "kind IN ('single', 'story')");

                            t.HasCheckConstraint("ck_post_state", "state IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("ck_post_topic", "topic IN ('cichlids', 'tanks', 'offtopic', 'contest', 'unknown')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.PostMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MediaItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_item_id");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_post_media");

                    b.HasIndex("MediaItemId")
                        .HasDatabaseName("ix_post_media_media_item_id");

                    b.HasIndex("PostId", "MediaItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_post_media_post_id_media_item_id");

                    b.ToTable("post_media", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.PostSpecies", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<long>("SpeciesId")
                        .HasColumnType("bigint")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_post_species");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_post_species_species_id");

                    b.HasIndex("PostId", "SpeciesId")
                        .IsUnique()
                        .HasDatabaseName("ix_post_species_post_id_species_id");

                    b.ToTable("post_species", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AvatarMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("avatar_media_id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalAvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("external_avatar_url");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<long?>("ProfileImageMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_image_media_id");

                    b.Property<DateTimeOffset?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_until");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.HasIndex("AvatarMediaId")
                        .HasDatabaseName("ix_profile_avatar_media_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_legacy_id");

                    b.HasIndex("ProfileImageMediaId")
                        .HasDatabaseName("ix_profile_profile_image_media_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_username");

                    b.ToTable("profile", "public", t =>
                        {
                            t.HasCheckConstraint("ck_profile_kind", "kind IN ('member', 'archived', 'system')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.ProfileIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_profile_identity");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_profile_identity_profile_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_identity_provider_subject");

                    b.ToTable("profile_identity", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LegacyCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_comment_id");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<long?>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<short>("Stars")
                        .HasColumnType("smallint")
                        .HasColumnName("stars");

                    b.Property<long?>("TankId")
                        .HasColumnType("bigint")
                        .HasColumnName("tank_id");

                    b.HasKey("Id")
                        .HasName("pk_rating");

                    b.HasIndex("LegacyCommentId")
                        .IsUnique()
                        .HasDatabaseName("ix_rating_legacy_comment_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_rating_post_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_rating_profile_id");

                    b.HasIndex("TankId")
                        .HasDatabaseName("ix_rating_tank_id");

                    b.ToTable("rating", "public", t =>
                        {
                            t.HasCheckConstraint("ck_rating_exactly_one_target", "(post_id IS NULL) <> (tank_id IS NULL)");

                            t.HasCheckConstraint("ck_rating_stars_range", "stars BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.SlugAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCanonical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_canonical");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_slug_alias");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasDatabaseName("ix_slug_alias_post_id")
                        .HasFilter("is_canonical = true");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_slug_alias_value");

                    b.ToTable("slug_alias", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Species", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Aggression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggression");

                    b.Property<string>("Breeding")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("breeding");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diet");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genus");

                    b.Property<string>("GhRange")
                        .HasColumnType("text")
                        .HasColumnName("gh_range");

                    b.Property<string>("Habitat")
                        .HasColumnType("text")
                        .HasColumnName("habitat");

                    b.Property<string>("IntraAggression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intra_aggression");

                    b.Property<string>("KhRange")
                        .HasColumnType("text")
                        .HasColumnName("kh_range");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("MaxSize")
                        .HasColumnType("text")
                        .HasColumnName("max_size");

                    b.Property<string>("Morphs")
                        .HasColumnType("text")
                        .HasColumnName("morphs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("PhRange")
                        .HasColumnType("text")
                        .HasColumnName("ph_range");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TemperatureRange")
                        .HasColumnType("text")
                        .HasColumnName("temperature_range");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_species_legacy_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_species_slug");

                    b.HasIndex("Genus", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_species_genus_name");

                    b.ToTable("species", "public", t =>
                        {
                            t.HasCheckConstraint("ck_species_aggression", "aggression IN ('unspecified', 'low', 'moderate', 'high')");

                            t.HasCheckConstraint("ck_species_breeding", "breeding IN ('unspecified', 'mouthbreeder', 'cave_breeder', 'substrate_breeder')");

                            t.HasCheckConstraint("ck_species_diet", "diet IN ('unspecified', 'omnivore', 'carnivore', 'herbivore', 'limnivore')");

                            t.HasCheckConstraint("ck_species_intra_aggression", "intra_aggression IN ('unspecified', 'low', 'moderate', 'high')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.SpeciesCommonName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("SpeciesId")
                        .HasColumnType("bigint")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_common_name");

                    b.HasIndex("SpeciesId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_species_common_name_species_id_name");

                    b.ToTable("species_common_name", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.SpeciesLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<long>("SpeciesId")
                        .HasColumnType("bigint")
                        .HasColumnName("species_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_species_link");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_species_link_species_id");

                    b.ToTable("species_link", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Tank", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decoration")
                        .HasColumnType("text")
                        .HasColumnName("decoration");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedByProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_profile_id");

                    b.Property<int?>("DepthValue")
                        .HasColumnType("integer")
                        .HasColumnName("depth_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DimensionUnit")
                        .HasColumnType("text")
                        .HasColumnName("dimension_unit");

                    b.Property<string>("Filtration")
                        .HasColumnType("text")
                        .HasColumnName("filtration");

                    b.Property<string>("Food")
                        .HasColumnType("text")
                        .HasColumnName("food");

                    b.Property<string>("Gravel")
                        .HasColumnType("text")
                        .HasColumnName("gravel");

                    b.Property<int?>("HeightValue")
                        .HasColumnType("integer")
                        .HasColumnName("height_value");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Light")
                        .HasColumnType("text")
                        .HasColumnName("light");

                    b.Property<string>("LightDuration")
                        .HasColumnType("text")
                        .HasColumnName("light_duration");

                    b.Property<long?>("MainMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("main_media_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Plants")
                        .HasColumnType("text")
                        .HasColumnName("plants");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Technic")
                        .HasColumnType("text")
                        .HasColumnName("technic");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("WaterGh")
                        .HasColumnType("text")
                        .HasColumnName("water_gh");

                    b.Property<string>("WaterKh")
                        .HasColumnType("text")
                        .HasColumnName("water_kh");

                    b.Property<string>("WaterNo2")
                        .HasColumnType("text")
                        .HasColumnName("water_no2");

                    b.Property<string>("WaterNo3")
                        .HasColumnType("text")
                        .HasColumnName("water_no3");

                    b.Property<string>("WaterNotes")
                        .HasColumnType("text")
                        .HasColumnName("water_notes");

                    b.Property<string>("WaterPh")
                        .HasColumnType("text")
                        .HasColumnName("water_ph");

                    b.Property<string>("WaterPo4")
                        .HasColumnType("text")
                        .HasColumnName("water_po4");

                    b.Property<int?>("WidthValue")
                        .HasColumnType("integer")
                        .HasColumnName("width_value");

                    b.HasKey("Id")
                        .HasName("pk_tank");

                    b.HasIndex("DeletedByProfileId")
                        .HasDatabaseName("ix_tank_deleted_by_profile_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_tank_legacy_id");

                    b.HasIndex("MainMediaId")
                        .HasDatabaseName("ix_tank_main_media_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_tank_profile_id");

                    b.ToTable("tank", "public", t =>
                        {
                            t.HasCheckConstraint("ck_tank_category", "category IS NULL OR category IN ('tanganyika', 'malawi', 'american', 'african', 'community', 'central_american', 'south_american')");

                            t.HasCheckConstraint("ck_tank_dimension_unit", "dimension_unit IS NULL OR dimension_unit IN ('cm', 'inch')");

                            t.HasCheckConstraint("ck_tank_state", "state IN ('draft', 'published')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.TankMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MediaItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<long>("TankId")
                        .HasColumnType("bigint")
                        .HasColumnName("tank_id");

                    b.HasKey("Id")
                        .HasName("pk_tank_media");

                    b.HasIndex("MediaItemId")
                        .HasDatabaseName("ix_tank_media_media_item_id");

                    b.HasIndex("TankId", "MediaItemId", "Section")
                        .IsUnique()
                        .HasDatabaseName("ix_tank_media_tank_id_media_item_id_section");

                    b.ToTable("tank_media", "public", t =>
                        {
                            t.HasCheckConstraint("ck_tank_media_section", "section IN ('showcase', 'decoration', 'technic')");
                        });
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.WebhookSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<string>>("EventTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("event_types");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_webhook_subscription");

                    b.ToTable("webhook_subscription", "public");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Collection", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collection_profiles_profile_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.CollectionEntry", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Collection", null)
                        .WithMany("Entries")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_entry_collection_collection_id");

                    b.HasOne("Cichlids.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_entry_posts_post_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("AuthorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comment_profiles_author_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("DeletedByProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comment_profiles_deleted_by_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comment_posts_post_id");

                    b.HasOne("Cichlids.Domain.Entities.Tank", null)
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comment_tanks_tank_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.CommentVote", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Comment", null)
                        .WithMany("Votes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_vote_comment_comment_id");

                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_vote_profiles_profile_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.DiscussionPost", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("AuthorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_discussion_post_profiles_author_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.DiscussionThread", null)
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discussion_post_discussion_threads_thread_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.DiscussionPostMedia", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.DiscussionPost", null)
                        .WithMany("Media")
                        .HasForeignKey("DiscussionPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discussion_post_media_discussion_posts_discussion_post_id");

                    b.HasOne("Cichlids.Domain.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discussion_post_media_media_items_media_item_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Follow", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("FollowerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follow_profiles_follower_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("TargetProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_profiles_target_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.Tank", null)
                        .WithMany()
                        .HasForeignKey("TargetTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_follow_tanks_target_tank_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Inhabitant", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inhabitant_species_species_id");

                    b.HasOne("Cichlids.Domain.Entities.Tank", null)
                        .WithMany("Inhabitants")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inhabitant_tanks_tank_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.MediaItem", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("OwnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_media_item_profiles_owner_profile_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.MediaVariant", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.MediaItem", null)
                        .WithMany("Variants")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_variant_media_item_media_item_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Post", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("AuthorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_profiles_author_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("DeletedByProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_post_profiles_deleted_by_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.Tank", null)
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_post_tanks_tank_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.PostMedia", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_media_media_item_media_item_id");

                    b.HasOne("Cichlids.Domain.Entities.Post", null)
                        .WithMany("Media")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_media_posts_post_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.PostSpecies", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Post", null)
                        .WithMany("Species")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_species_posts_post_id");

                    b.HasOne("Cichlids.Domain.Entities.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_species_species_species_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Profile", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("AvatarMediaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_profile_media_item_avatar_media_id");

                    b.HasOne("Cichlids.Domain.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("ProfileImageMediaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_profile_media_item_profile_image_media_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.ProfileIdentity", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany("Identities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_identity_profile_profile_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Rating", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rating_post_post_id");

                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rating_profile_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.Tank", null)
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rating_tanks_tank_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.SlugAlias", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_slug_alias_post_post_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.SpeciesCommonName", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Species", null)
                        .WithMany("CommonNames")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_common_name_species_species_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.SpeciesLink", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Species", null)
                        .WithMany("Links")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_link_species_species_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Tank", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("DeletedByProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tank_profile_deleted_by_profile_id");

                    b.HasOne("Cichlids.Domain.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MainMediaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tank_media_item_main_media_id");

                    b.HasOne("Cichlids.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tank_profile_profile_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.TankMedia", b =>
                {
                    b.HasOne("Cichlids.Domain.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tank_media_media_item_media_item_id");

                    b.HasOne("Cichlids.Domain.Entities.Tank", null)
                        .WithMany("Media")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tank_media_tanks_tank_id");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.DiscussionPost", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.DiscussionThread", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.MediaItem", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Post", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Profile", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Species", b =>
                {
                    b.Navigation("CommonNames");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Cichlids.Domain.Entities.Tank", b =>
                {
                    b.Navigation("Inhabitants");

                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
