<?php
/**
 * Language labels for database tables/fields belonging to extension "user_cichlids"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"user_cichlids_tanks" => "Tanks",	
		"user_cichlids_tanks.category" => "Category",	
		"user_cichlids_tanks.width" => "Width",	
		"user_cichlids_tanks.height" => "Height",	
		"user_cichlids_tanks.depth" => "Depth",	
		"user_cichlids_tanks.specials" => "Specials",	
		"user_cichlids_tanks.gravel" => "Gravel",	
		"user_cichlids_tanks.plants" => "Plants",	
		"user_cichlids_tanks.more_deco" => "More Decoration",	
		"user_cichlids_tanks.light" => "Light",	
		"user_cichlids_tanks.light_duration" => "Light Duration",	
		"user_cichlids_tanks.filtration" => "Filtration",	
		"user_cichlids_tanks.more_tec" => "More Technics",	
		"user_cichlids_tanks.water_ph" => "pH",	
		"user_cichlids_tanks.water_kh" => "KH",	
		"user_cichlids_tanks.water_gh" => "GH",	
		"user_cichlids_tanks.water_no2" => "NO2",	
		"user_cichlids_tanks.water_no3" => "NO3",	
		"user_cichlids_tanks.water_po4" => "PO4",	
		"user_cichlids_tanks.food" => "food",	
		"user_cichlids_category" => "Category",	
		"user_cichlids_category.title" => "Category",	
		"user_cichlids_species" => "Species",	
		"user_cichlids_species.genus" => "Genus",	
		"user_cichlids_species.species" => "Species",	
		"user_cichlids_species.common" => "Common Names",	
		"user_cichlids_species.category" => "Category",	
		"user_cichlids_species.ph" => "pH",	
		"user_cichlids_species.gh" => "Hardness",	
		"user_cichlids_species.temp" => "Temperature",	
		"user_cichlids_species.max_size" => "Max size",	
		"user_cichlids_species.origin" => "Geographic Origin",	
		"user_cichlids_species.habitat" => "Habitat",	
		"user_cichlids_species.kh" => "KH",	
		"user_cichlids_species.breeding.I.0" => "unspecified",	
		"user_cichlids_species.breeding.I.1" => "Mouthbreeder",	
		"user_cichlids_species.breeding.I.2" => "Cave Breeder",	
		"user_cichlids_species.breeding.I.3" => "Substrate Breeder",	
		"user_cichlids_species.breeding" => "Breeding",	
		"user_cichlids_species.diet.I.0" => "unspecified",	
		"user_cichlids_species.diet.I.1" => "Omnivore",	
		"user_cichlids_species.diet.I.2" => "Carnivore",	
		"user_cichlids_species.diet.I.3" => "Herbivore",	
		"user_cichlids_species.diet.I.4" => "Limnivore",	
		"user_cichlids_species.diet" => "Diet",	
		"user_cichlids_species.aggro.I.0" => "n/a",	
		"user_cichlids_species.aggro.I.1" => "Low",	
		"user_cichlids_species.aggro.I.2" => "Moderate",	
		"user_cichlids_species.aggro.I.3" => "High",	
		"user_cichlids_species.aggro" => "Aggro",	
		"user_cichlids_species.inner_aggro" => "Conspefic Aggro",	
		"user_cichlids_species.description" => "Description",	
		"user_cichlids_species.links" => "Links",	
		"user_cichlids_species.link_texts" => "Link Texts",	
		"user_cichlids_common_name" => "Common Name",	
		"user_cichlids_pictures" => "Pictures",	
		"user_cichlids_pictures.title" => "Title",	
		"user_cichlids_pictures.fe_user" => "Frontend User",	
		"user_cichlids_pictures.species" => "Species",	
		"user_cichlids_pictures.image" => "Image",	
		"user_cichlids_pictures.description" => "Description",	
		"user_cichlids_comments" => "Comments",	
		"user_cichlids_comments.type.I.0" => "Tanks",	
		"user_cichlids_comments.type.I.1" => "Pictures",	
		"user_cichlids_comments.type.I.2" => "Species",	
		"user_cichlids_comments.type" => "Type",	
		"user_cichlids_comments.item" => "Commented Item",	
		"user_cichlids_comments.parent" => "Parent",	
		"user_cichlids_comments.rating" => "Rating",	
		"user_cichlids_genus_names" => "Genus Names",	
		"user_cichlids_genus_names.title" => "Title",	
		"user_cichlids_species_names" => "Species Names",	
		"user_cichlids_species_names.title" => "Title",	
		"tt_content.list_type_pi1" => "Cichlids.com",	
		"tt_content.list_type_pi2" => "Cichlids.com User Upload",	
		"tt_content.list_type_pi3" => "Cichlids.com New",	
	),
);
?>
