namespace Cichlids.Domain.Entities;

/// <summary>
/// A domain event recorded in the same transaction as the change that raised it, for later
/// dispatch to registered webhook subscribers.
/// </summary>
public class OutboxEvent
{
    /// <summary>
    /// Generated by the writer (a version 7 UUID) so the row can be created and referenced
    /// before it is inserted, without a database round-trip.
    /// </summary>
    public Guid Id { get; set; }

    public DateTimeOffset OccurredAt { get; set; }
    public string EventType { get; set; } = string.Empty;
    public string AggregateType { get; set; } = string.Empty;
    public string AggregateId { get; set; } = string.Empty;
    public string Payload { get; set; } = string.Empty;
    public DateTimeOffset? DispatchedAt { get; set; }
    public int AttemptCount { get; set; }
    public string? LastError { get; set; }
}
