NameVirtualHost *:80

<VirtualHost *:80>
        Servername www.cichlids.com
        <Directory "/var/www/html">
                Options Indexes FollowSymLinks
                AllowOverride All

		php_value upload_max_filesize 50M
		php_value post_max_size 50M
		php_value max_input_time -1
        </Directory>
</VirtualHost>

