server {
	listen 80 default_server;
	listen [::]:80 default_server;

        server_name www.cichlids.com;

	client_max_body_size 20M;

     	location / {
                return 301 https://www.cichlids.com$request_uri;
        }
}

server {
	listen 80;
	listen [::]:80;
        server_name cichlids.com;
        rewrite .* https://www.cichlids.com$request_uri permanent;
}


server {
	listen 80;
	listen       [::]:80;
        server_name  api.cichlids.fishauth.net cichlids.fishauth.net;

    	location / {
                return         301 https://$host$request_uri;
        }
}

server {
	listen 80;
	listen [::]:80;
        server_name dev.cichlids.com;

        rewrite .* https://dev.cichlids.com$request_uri permanent;
}
