#!/usr/bin/env python3
"""Generate the ADR list in adr/index.md from the ADR files themselves.

The list of ADRs is derived from the files in ``adr/`` by globbing, so it never
has to be maintained by hand. Each ADR's number, title, and status are read from
its first heading (``# ADR-NNNN: <title>``) and its ``- **Status:** <status>``
line. The rendered table is written between the marker comments in ``index.md``.

Usage:
    python tools/generate_adr_index.py          # rewrite the list in place
    python tools/generate_adr_index.py --check   # exit non-zero if out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ADR_DIR = Path(__file__).resolve().parent.parent / "adr"
INDEX_FILE = ADR_DIR / "index.md"

# ADR files are NNNN-kebab-title.md; 0000 is the template and is excluded.
ADR_GLOB = "[0-9][0-9][0-9][0-9]-*.md"
TEMPLATE_STEM_PREFIX = "0000-"

BEGIN_MARKER = "<!-- BEGIN ADR LIST (generated by tools/generate_adr_index.py — do not edit by hand) -->"
END_MARKER = "<!-- END ADR LIST -->"

TITLE_RE = re.compile(r"^#\s+ADR-(\d{4}):\s+(.*?)\s*$", re.MULTILINE)
STATUS_RE = re.compile(r"^-\s+\*\*Status:\*\*\s+(.*?)\s*$", re.MULTILINE)


def parse_adr(path: Path) -> tuple[str, str, str]:
    """Return (number, title, status) for a single ADR file."""
    text = path.read_text(encoding="utf-8")
    title_match = TITLE_RE.search(text)
    if not title_match:
        raise ValueError(f"{path.name}: no '# ADR-NNNN: <title>' heading found")
    status_match = STATUS_RE.search(text)
    status = status_match.group(1) if status_match else "Unknown"
    return title_match.group(1), title_match.group(2), status


def render_table() -> str:
    rows = []
    for path in sorted(ADR_DIR.glob(ADR_GLOB)):
        if path.name.startswith(TEMPLATE_STEM_PREFIX):
            continue
        number, title, status = parse_adr(path)
        rows.append(f"| [{number}]({path.name}) | {title} | {status} |")

    table = ["| No. | Title | Status |", "|---|---|---|", *rows]
    return "\n".join(table)


def render_index(current: str, table: str) -> str:
    if BEGIN_MARKER not in current or END_MARKER not in current:
        raise ValueError(
            f"{INDEX_FILE.name}: markers not found; expected "
            f"{BEGIN_MARKER!r} and {END_MARKER!r}"
        )
    block = f"{BEGIN_MARKER}\n{table}\n{END_MARKER}"
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    return pattern.sub(block, current)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if index.md is out of date instead of rewriting it",
    )
    args = parser.parse_args()

    current = INDEX_FILE.read_text(encoding="utf-8")
    updated = render_index(current, render_table())

    if args.check:
        if current != updated:
            print(
                f"{INDEX_FILE.name} is out of date; run "
                "tools/generate_adr_index.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if current != updated:
        INDEX_FILE.write_text(updated, encoding="utf-8")
        print(f"Updated {INDEX_FILE.name}")
    else:
        print(f"{INDEX_FILE.name} already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
